DROP SCHEMA shoppingcart;
CREATE SCHEMA shoppingcart;

CREATE TABLE shoppingcart.USERS (
	USER_ID NUMERIC(10) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50),
    BIO VARCHAR(200),
    EMAIL VARCHAR(200) NOT NULL,
    AREA_OF_INTEREST VARCHAR(300),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE shoppingcart.PRODUCTS(
	PRODUCT_ID NUMERIC(10) NOT NULL,
    NAME VARCHAR (100) NOT NULL,
    PRICE NUMERIC(10) NOT NULL,
    IMAGE LONGBLOB,
    DESCRIPTION VARCHAR(200),
    TOTAL_PRODUCTS_INVENTORY NUMERIC(10) NOT NULL,
    STATUS BOOLEAN NOT NULL,
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE shoppingcart.ORDER_HISTORY(
	ORDER_ID NUMERIC(10) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    USER_ID NUMERIC (10),
    PRODUCT_ID NUMERIC (10),
    PRIMARY KEY (ORDER_ID)
);

CREATE TABLE shoppingcart.WISHLIST(
	WISH_ID NUMERIC(10) NOT NULL PRIMARY KEY,
    USER_ID NUMERIC(10),
    PRODUCT_ID NUMERIC(10)
);

select * from shoppingcart.USERS
select * from shoppingcart.PRODUCTS
select * from shoppingcart.ORDER_HISTORY
select * from shoppingcart.WISHLIST

DROP TABLE shoppingcart.WISHLIST

insert into shoppingcart.USERS values(1"Sarahi2", "Jose2", "bio2","sarahichic2a@hotmail.com", "music");
insert into shoppingcart.PRODUCTS values(1,                                


ALTER TABLE shoppingcart.ORDER_HISTORY
ADD FOREIGN KEY (USER_ID) REFERENCES shoppingcart.USERS(USER_ID),
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES shoppingcart.PRODUCTS(PRODUCT_ID);

ALTER TABLE shoppingcart.WISHLIST
ADD FOREIGN KEY (USER_ID) REFERENCES shoppingcart.USERS(USER_ID),
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES shoppingcart.PRODUCTS(PRODUCT_ID);
    






